import { StyleSheet } from 'react-native';
import colors from '../../../theme/colors';
import typography from '../../../theme/typography';
import spacing from '../../../theme/spacing';

export default StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    padding: spacing.screenPadding,
  },
  modalCard: {
    backgroundColor: colors.bg.duskRaised,
    borderRadius: 8,
    padding: spacing.cardPadding,
    borderWidth: 1.5,
    borderColor: '#3D3560',
    gap: spacing.sm,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  modalTitle: {
    ...typography.headingLg,
    color: colors.text.onDark.primary,
    fontWeight: '800',
    marginBottom: spacing.xs,
  },
  modalSub: {
    ...typography.bodyMd,
    color: colors.text.onDark.secondary,
    fontSize: 12,
  },
  stepTabRow: {
    flexDirection: 'row',
    backgroundColor: '#171326',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3D3560',
    padding: 4,
    gap: 6,
    marginBottom: 6,
  },
  stepTabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 5,
  },
  stepTabBtnActive: {
    backgroundColor: 'rgba(242, 200, 75, 0.2)',
    borderWidth: 1,
    borderColor: colors.accent.gold,
  },
  stepTabText: {
    ...typography.displayPixelXs,
    fontSize: 8.5,
    color: colors.text.onDark.secondary,
  },
  stepTabTextActive: {
    color: colors.accent.gold,
    fontWeight: '900',
  },
  coordsChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(62, 207, 142, 0.12)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.accent.green,
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 6,
  },
  coordsChipText: {
    ...typography.displayPixelXs,
    fontSize: 7.5,
    color: colors.accent.green,
    flex: 1,
  },
  changeLocLink: {
    ...typography.caption,
    fontSize: 10,
    color: colors.accent.gold,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  questInfoNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: 'rgba(126, 117, 160, 0.12)',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3D3560',
  },
  questInfoNoteText: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.onDark.secondary,
    flex: 1,
    lineHeight: 14,
  },
  questPickerRow: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 2,
  },
  questPickerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1E1A33',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#3D3560',
  },
  questPickerChipActive: {
    backgroundColor: 'rgba(242, 200, 75, 0.18)',
    borderColor: colors.accent.gold,
  },
  questPickerChipText: {
    ...typography.caption,
    fontSize: 10.5,
    fontWeight: '700',
    color: colors.text.onDark.secondary,
  },
  questPickerChipTextActive: {
    color: colors.accent.gold,
    fontWeight: '800',
  },
  noQuestNoticeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(232, 102, 75, 0.12)',
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(232, 102, 75, 0.3)',
  },
  noQuestNoticeText: {
    ...typography.caption,
    fontSize: 10,
    color: colors.accent.coral,
    flex: 1,
  },
  fieldGroup: {
    gap: 3,
  },
  inputLabel: {
    ...typography.displayPixelXs,
    fontSize: 7.5,
    color: colors.accent.gold,
    letterSpacing: 0.8,
  },
  inputSubLabel: {
    ...typography.captionBold,
    fontSize: 9.5,
    color: colors.text.onDark.secondary,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: colors.bg.dusk,
    borderWidth: 1,
    borderColor: '#4A4170',
    borderRadius: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.text.onDark.primary,
    ...typography.bodyMd,
    fontSize: 13,
  },
  inlineInputs: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  autoQrPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: '#171329',
    borderRadius: 6,
    padding: spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(242, 200, 75, 0.25)',
  },
  autoQrTitle: {
    ...typography.displayPixelXs,
    fontSize: 7.5,
    color: colors.accent.gold,
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  autoQrSub: {
    ...typography.caption,
    fontSize: 9.5,
    color: colors.text.onDark.secondary,
    lineHeight: 13,
  },
  qrImageContainer: {
    width: 200,
    height: 200,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: spacing.sm,
    borderWidth: 2,
    borderColor: colors.accent.gold,
  },
  qrImage: {
    width: 184,
    height: 184,
    borderRadius: 4,
  },
  tokenPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1A33',
    borderWidth: 1,
    borderColor: '#4E4473',
    borderRadius: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    gap: 6,
    maxWidth: '100%',
  },
  tokenLabel: {
    ...typography.displayPixelXs,
    fontSize: 8,
    color: colors.accent.gold,
  },
  tokenVal: {
    ...typography.mono,
    fontSize: 11,
    color: colors.text.onDark.primary,
    flexShrink: 1,
  },
  copyHintText: {
    ...typography.caption,
    fontSize: 8,
    color: colors.text.onDark.secondary,
    fontWeight: 'bold',
  },
  qrPrintTip: {
    ...typography.caption,
    fontSize: 10,
    color: colors.text.onDark.secondary,
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 6,
  },
  qrShareBtn: {
    flex: 1.5,
    backgroundColor: colors.accent.gold,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrShareBtnText: {
    ...typography.captionBold,
    color: colors.bg.dusk,
    fontSize: 12,
  },
  modalBtnRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  modalCancel: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#4A4170',
    alignItems: 'center',
  },
  modalCancelText: {
    ...typography.bodyMd,
    color: colors.text.onDark.secondary,
  },
  modalSave: {
    flex: 1.2,
    backgroundColor: colors.accent.gold,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  modalSaveText: {
    ...typography.bodyMdBold,
    color: colors.bg.dusk,
  },
  playerPreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#130F20',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#3D3560',
  },
  banAvatarBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: 'rgba(232, 102, 75, 0.18)',
    borderWidth: 1.5,
    borderColor: colors.accent.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  banAvatarText: {
    ...typography.headingLg,
    color: colors.accent.coral,
    fontWeight: '900',
  },
  banPlayerName: {
    ...typography.bodyMdBold,
    color: colors.text.onDark.primary,
    fontSize: 14,
  },
  banPlayerEmail: {
    ...typography.caption,
    color: colors.text.onDark.secondary,
    fontSize: 11,
  },
  deleteAvatarBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: 'rgba(232, 102, 75, 0.18)',
    borderWidth: 1.5,
    borderColor: colors.accent.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteAvatarText: {
    ...typography.headingLg,
    color: colors.accent.coral,
    fontWeight: '900',
  },
  deletePlayerName: {
    ...typography.bodyMdBold,
    color: colors.text.onDark.primary,
    fontSize: 14,
  },
  deletePlayerEmail: {
    ...typography.caption,
    color: colors.text.onDark.secondary,
    fontSize: 11,
  },
  deletePill: {
    backgroundColor: '#1E1A33',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#3D3560',
  },
  deletePillText: {
    ...typography.displayPixelXs,
    fontSize: 7,
    color: colors.text.onDark.secondary,
  },
  deleteWarningBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(232, 102, 75, 0.12)',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(232, 102, 75, 0.3)',
  },
  deleteWarningText: {
    ...typography.bodySm,
    fontSize: 11,
    color: colors.accent.coral,
    flex: 1,
    lineHeight: 16,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  categoryPill: {
    flex: 1,
    minWidth: '45%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#1C172E',
    borderWidth: 1,
    borderColor: '#3D3560',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  categoryPillActive: {
    borderColor: colors.accent.gold,
    backgroundColor: '#2A2010',
  },
  categoryPillText: {
    ...typography.captionBold,
    fontSize: 11,
    color: colors.text.onDark.secondary,
  },
  categoryPillTextActive: {
    color: colors.accent.gold,
    fontWeight: '800',
  },
  verificationBadgeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(95, 191, 122, 0.1)',
    borderWidth: 1,
    borderColor: colors.accent.green,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 5,
    marginBottom: 4,
  },
  verificationBadgeText: {
    ...typography.captionBold,
    fontSize: 9,
    color: colors.accent.green,
    letterSpacing: 0.5,
  },
});
